### ISSUE TITLE
register error

### ISSUE THREAD

**Issue by DaveHu-TVU** [NVIDIA/nvnmos#6]
Hi all, 
     it will report this error when I run nvnmos-example, 
Registration request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_behaviour]
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_system_behaviour]
Registration request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_behaviour]
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_system_behaviour]
Registration request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_behaviour]
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_system_behaviour]
Registration request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_behaviour]
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_system_behaviour]
Registration request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_behaviour]
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113] [20:node_system_behaviour]

What local configuration is this related to? How should I troubleshoot this issue, thanks!

**Comment by garethsb** [comment]
Hi @DaveHu-TVU, please would you share a bit more about your setup?

* What OS?
* What command did you run, like `nvnmos-example nmos-api.local 8080 192.0.2.0`?
* Where is your NMOS Registry running? Can you `ping` it from the host or container where you run `nvnmos-example`? Can you also access it via HTTP?
* Please would you try enabling verbose logging? Add `-40` at the end of the above command?

Thanks!

**Comment by DaveHu-TVU** [comment]
What OS?
----->Ubuntu 24.04
What command did you run, like nvnmos-example nmos-api.local 8080 192.0.2.0?
-----> Yes, ./nvnmos-example nmos-api.local 8088 192.168.1.110
Where is your NMOS Registry running? Can you ping it from the host or container where you run nvnmos-example? Can you also access it via HTTP?
---->NMOS Server is running in 192.168.1.114, I used the Easy-nmos which IP including (192.168.1.201, 192.168.1.202, 192.168.1.203)
and nvnmos-example running 192.168.1.110, which including Nvidia ConnectX-6 Lx Card,
I tried ping :
[root@TVU46BB:/data/dave/newnmos]# ping 192.168.1.201 
PING 192.168.1.201 (192.168.1.201) 56(84) bytes of data.
From 192.168.1.215 icmp_seq=1 Destination Host Unreachable
From 192.168.1.215 icmp_seq=2 Destination Host Unreachable
From 192.168.1.215 icmp_seq=3 Destination Host Unreachable
^C
--- 192.168.1.201 ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4103ms
pipe 4
[root@TVU46BB:/data/dave/newnmos]# ping 192.168.1.201 -I enp3s0
PING 192.168.1.201 (192.168.1.201) from 192.168.1.110 enp3s0: 56(84) bytes of data.
64 bytes from 192.168.1.201: icmp_seq=1 ttl=64 time=0.139 ms
64 bytes from 192.168.1.201: icmp_seq=2 ttl=64 time=0.155 ms
64 bytes from 192.168.1.201: icmp_seq=3 ttl=64 time=0.169 ms
^C
--- 192.168.1.201 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2048ms
rtt min/avg/max/mdev = 0.139/0.154/0.169/0.012 ms
[root@TVU46BB:/data/dave/newnmos]# ping 192.168.1.201 -I enp3s^C
[root@TVU46BB:/data/dave/newnmos]# ip ro
default via 10.12.0.3 dev enp4s0 proto dhcp src 10.12.32.76 metric 102 
default via 192.168.1.1 dev enp3s0 proto dhcp src 192.168.1.110 metric 103 
10.12.0.0/18 dev enp4s0 proto kernel scope link src 10.12.32.76 metric 102 
169.254.0.0/24 dev docker0 proto kernel scope link src 169.254.0.1 
192.168.1.0/24 dev enp1s0f0np0 proto kernel scope link src 192.168.1.215 
192.168.1.0/24 dev enp1s0f1np1 proto kernel scope link src 192.168.1.216 
192.168.1.0/24 dev enp3s0 proto kernel scope link src 192.168.1.110 metric 103 
  
you can check the ifconfig 

Please would you try enabling verbose logging? Add -40 at the end of the above command?
  see the nvnmos.log
[nvnmos.tar.gz](https://github.com/user-attachments/files/17957434/nvnmos.tar.gz)

**Comment by DaveHu-TVU** [comment]
It looks like the system is using enp1s0f0np0 as the default NIC, which is preventing example from working.

**Comment by DaveHu-TVU** [comment]
Thanks! I think I find the root cause

**Comment by garethsb** [comment]
Yes, given the `ip ro` output it makes sense. Per the nvnmos log, the DNS-SD implementation is able to discover the NMOS Registry at 192.168.1.201 on interface 2 (presumably enp3s0, but you can use `ip link show` to translate this to an interface name), but then due to the defined routes and metrics, the HTTP request was being routed via enp1s0f0np0. It might be beneficial to have a different subnet for each interface if possible.
